name: Build API

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  github-username:
    description: 'GitHub username for authentication'
    required: true

outputs:
  api-artifacts:
    description: 'Built API artifacts'
    value: 'build/distributions/consent-history-api.zip'

runs:
  using: 'composite'
  steps:
    - name: Check out package
      uses: actions/checkout@v4
      with:
        # Specify repository so this action can be run from other repositories
        repository: Consent-Management-Platform/consent-history-api
        path: consent-history-api
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 21
    - name: Run gradle build
      run: gradle wrapper build
      shell: bash
      working-directory: consent-history-api
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_USERNAME: ${{ inputs.github-username }}
